### ISSUE TITLE
Getting an error while using the service with proguard

### ISSUE THREAD

**Issue by kumarshorav11** [KoolShailesh/dev#1]
`<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Sep 13 16:49:19 IST 2019</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Could not write JSON: No serializer found for class com.xxx.c.c and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.hcl.c.c and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.HashSet[0])</div></body></html>`

If I am hitting the service endpoint "getallteams", above error is coming. I tried to fix but unable to fix it. I am not sure, this is working or not? I also tried to use answer as provided :
[https://stackoverflow.com/questions/48869659/proguard-causes-jackson-error](url)

Please help me fixing this.

**Comment by KoolShailesh** [comment]
Actually this is project I use for multiple purpose, last time I verified obfuscation on same, didn't bother if rest is working, I will fix same

**Comment by KoolShailesh** [comment]
fix the code to work with obfuscation , If running war with java -jar then use URL

http://localhost:8080/tournament/getallteams

and if running code within IDE, you can use URL http://localhost:8080/prokabaddi/tournament/getallteams
